name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint coverage pytest
    - name: Pylint
      run: |
        pylint --rcfile=.pylintrc src/glados
    - name: Build
      run: |
        pip install .
        glados -v
    - name: Test
      run: |
        cd tests
        PYTHONPATH=$(pwd)/../src:$PYTHONPATH \
          coverage run -m pytest
        coverage report -m > coverage.txt
        coverage json

        cat coverage.txt
        COV_PCT=$(tail -n1 coverage.txt | awk '{print $NF}' | sed 's/%//')
        if [[ $COV_PCT -lt 80 ]]; then
          echo "FAIL: Coverage `$COV_PCT`  < 80%"
          exit 1
        else
          echo "PASS: Coverage $COV_PCT >= 80%"
        fi
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: tests
